<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <IsPackable>false</IsPackable>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ef8MultiContextOrders\Ef8MultiContextOrdersFixture.csproj" />
    <ProjectReference Include="..\Ef8MultiContextCustomers\Ef8MultiContextCustomersFixture.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
  </ItemGroup>
</Project>
